# Generated by Django 5.2.8 on 2026-09-10 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_category_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='درباره ی محصول', max_length=200, verbose_name='عنوان دیدگاه')),
                ('text', models.TextField(verbose_name='متن دیدگاه')),
                ('recommendation', models.CharField(choices=[('recommended', 'پیشنهاد می\u200cشود'), ('not_recommended', 'پیشنهاد نمی\u200cشود')], default='recommended', max_length=20, verbose_name='پیشنهاد')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
